### ISSUE TITLE
Printing a div with overflow-y: scroll

### ISSUE THREAD

**Issue by RoelAlblas** [DoersGuild/jQuery.print#103]
### Expected behaviour

Printing a DIV with an overflow, will print the whole DIV. Not only the visible text on the screen.

### Observed behaviour

While printing, a part of the DIV will not be printed because it is not visible on the screen.

### Steps to reproduce the issue

Create a DIV with the following styling. Create a text larger then the height of the DIV and print.

height: 800px; max-height: 800px; overflow-x: hidden; overflow-y: scroll;

### Simplified demo link reproducing the issue

none

### jQuery, jQuery.print version

jQuery: v2.1.4
jQuery.print: v1.6.0

### Browser and operating system

Chrome and Windows 10

**Comment by sathvikp** [comment]
Try targetting the parent element and ensure that the CSS is carried forward to the print

The plugin only puts your selected element and styles into an iframe/window and calls print on the same


---- On Fri, 01 Feb 2019 20:09:23 +0530 notifications@github.com wrote ----


Expected behaviour

Printing a DIV with an overflow, will print the whole DIV. Not only the visible text on the screen.

Observed behaviour

While printing, a part of the DIV will not be printed because it is not visible on the screen.

Steps to reproduce the issue

Create a DIV with the following styling. Create a text larger then the height of the DIV and print.

height: 800px; max-height: 800px; overflow-x: hidden; overflow-y: scroll;

Simplified demo link reproducing the issue

none

jQuery, jQuery.print version

jQuery: v2.1.4
jQuery.print: v1.6.0

Browser and operating system

Chrome and Windows 10

**Comment by RoelAlblas** [comment]
Hi!

Could you please tell me how to do this?

I've got the HTML like below. The content property is a Gridview rendered by DevExpress Library. So all styling is in there:

`                
var adjustedContent = "";
`

`
                adjustedContent += "<span class=\"fas fa-print\" style=\"font-size:18px; color:Black !important; cursor:pointer; margin: 10px;\" onclick=\"$('#unloadReport').print();\"></span>";
`


`
                adjustedContent += "<div id=\"unloadReport\" style=\"height: 800px; max-height: 800px; overflow-x: hidden; overflow-y: scroll;\">" + content + "</div>";
`

Thank you!

**Comment by sathvikp** [comment]
Please create a JSFiddle or another simplified demo so that you can get help with your specific case. Thank you


---- On Tue, 26 Feb 2019 15:46:33 +0530 notifications@github.com wrote ----



Hi!

Could you please tell me how to do this?

I've got the HTML like below. The content property is a Gridview rendered by DevExpress Library. So all styling is in there:

var adjustedContent = "";

adjustedContent += "<span class=\"fas fa-print\" style=\"font-size:18px; color:Black !important; cursor:pointer; margin: 10px;\" onclick=\"$('#unloadReport').print();\"></span>";

adjustedContent += "<div id=\"unloadReport\" style=\"height: 800px; max-height: 800px; overflow-x: hidden; overflow-y: scroll;\">" + content + "</div>";

Thank you!

**Comment by RoelAlblas** [comment]
https://jsfiddle.net/RoelAlblas/760tykfn/#&togetherjs=mHQFDEmu6A

**Comment by RoelAlblas** [comment]
Problem solved in this jsfiddle: https://jsfiddle.net/RoelAlblas/hg8ue0xp/
