### ISSUE TITLE
not tranfer values from forms

### ISSUE THREAD

**Issue by arcanisgk** [DoersGuild/jQuery.print#11]
Hello friend, I am using the script to print the contents of a div, the content is a form that is empty originally, then the user fills data and the idea is to print the form and with the data, but when printing, the print all empty fields, not working as a windows.print (). any solution for this?

**Comment by manikor** [comment]
I think I understands what he was saying. I ran into something similar.

I use jquery to populate a input field, and when I did this and used jquery.print() the value was not displaying when it print, but if I did ctrl + p and printed the page without jquery.print() the value displayed corrected.

I don't know the root cause, but I did figure out a work around.

Before I populated the value as such: $('#input_id').val('some value!');

Now, when I do this: $('#input_id').attr('value', 'some value!')' it prints fine.

Hope this helps,

**Comment by sathvikp** [comment]
Thanks, that makes perfect sense
The plugin works by adding your elements' HTML content (via jQuery.clone + jQuery.html) to an iframe/window and printing it, so dynamic form values are not updated.
The latest version (v1.3.0) addresses this by [manually adding each input's values](https://github.com/DoersGuild/jQuery.print/commit/8e37c9762d6a38ad72afb676bcea71008089438a), as you suggested here.
Thanks!
