### ISSUE TITLE
Print multiple selectors

### ISSUE THREAD

**Issue by fluxxus** [DoersGuild/jQuery.print#13]
Hi, thanks for the great plugin!

I have two simple questions, since I don't have an printer, so I can't really test.
1. Can I print multiple div's, for example
   `$('#print-content', #print-content2).print();`
2. Can I print elements that are set to display:none ?

Thanks

**Comment by ryanchamp-ICE** [comment]
Hello... This is a great plugin!

Minor issue but I just wanted to point out that it appears that printing with multiple selectors only works if you do
`$.print('#print-content, #print-content2');`
and not
`$('#print-content, #print-content2').print();`

I looked at it a little bit and it appears to be around this code here:
```
if (self instanceof $) {
            // Get the node if it is a jQuery object
            self = self.get(0);
}
```

If the selector `'#print-content, #print-content2'` brings back a collection, the plugin will only select the first DOM element because of the above code. Not sure if this was by design, but it would seem to me that the plugin should operate the same way regardless of which way you call it.

Thanks again! I really like your plugin. Great stuff!
