### ISSUE TITLE
When print, Uncaught ReferenceError: jQuery is not defined appears

### ISSUE THREAD

**Issue by Francks11** [DoersGuild/jQuery.print#24]
Hello,

I have an issue when I use jQuery.print plugin.

When I click to button print, I have following errors :

Uncaught ReferenceError: jQuery is not defined
Uncaught ReferenceError: head is not defined

I think that messages appear because I print a div and in this div, the jQuery and head script are not included.

The script are included in head and not in the div.

It is possible to copy the script of head tag when print a portion of page?

Thanks

**Comment by sathvikp** [comment]
Could you kindly share an example/demo snippet, perhaps on jsfiddle, so
that I can better understand the issue?

Thanks

**Comment by Francks11** [comment]
Hi @sathvikp 

I have simplified the code. You can find here a example : 

https://jsfiddle.net/Francks11/mz4hoLop/4/

When you click to Print link, you can see the error in the console : 

![capture](https://cloud.githubusercontent.com/assets/3995851/9468458/0e4a3526-4b42-11e5-9d9c-7c310a032944.png)

How can we print div which contains script? Its works but errors appears in console...
How can we avoid this?

Thanks

**Comment by sathvikp** [comment]
Thanks, please use the `noPrintSelector` option to skip script tags, like `noPrintSelector: 'script'` as shown in this Fiddle - https://jsfiddle.net/mz4hoLop/6/, because they may not be executed anyways.

You could also try to `prepend` the `script` tags on the page with `prepend: 'script'` to try and actually run the script on the snippet's printing page, but there is no guarantee that it will be executed before printing, as shown on this snippet  - https://jsfiddle.net/mz4hoLop/7/. If it is important that you run a script on the element, you're better off doing before calling `jQuery.print`.

**Comment by Francks11** [comment]
Ok thanks. I try it tomorrow.
