### ISSUE TITLE
Background color on table caption & JQuery Charts not showing

### ISSUE THREAD

**Issue by borgymanotoy** [DoersGuild/jQuery.print#26]
Hello,

I have a separate CSS that I called using stylesheet option, it contains a rule that sets the background color of the table caption. Also, I have a chart (JQPlot Chart).

The problem now is when I print, the chart is blank.. only the tables, and the table caption background is not shown (I was expecting a blackground color with white text, but I only got white background with black text).

I do not know what to set to have it look like I wanted it to.

THanks

**Comment by sathvikp** [comment]
Hi, could you please create a simple demo of the same on a site like JSFiddle so that I can help you better. jQuery.print clones your element and puts it in an iframe before printing the iframe, and depending on how the JQPlot renders the chart, it might need additional CSS or JS to render properly on the printing iframe ...

Regarding the custom background color, kindly see if http://stackoverflow.com/a/15253634/937891 helps
