### ISSUE TITLE
print a div contain a select dropdown empty

### ISSUE THREAD

**Issue by syrakozz** [DoersGuild/jQuery.print#32]
print a div contain a select dropdown show  empty value

**Comment by sathvikp** [comment]
This is likely an issue with your CSS.
Could you please create a demo JSFiddle so that I can better understand
your issue?

Thanks!

On 4 December 2015 at 13:40, syrakozz <notifications@github.com> wrote:

> when i use its print 2 page instead of one and the other one is empty
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DoersGuild/jQuery.print/issues/32>.
>



-- 
Sathvik
Doers' Guild
<http://t.sidekickopen30.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LqWkjW6443-21q0T7nW3Ljg7x56dK-rf8GfzwT02?t=http%3A%2F%2Fwww.doersguild.com%2F&si=5680052904132608&pi=b0275b81-1d94-4271-b6ae-92e63960a9ea>
RWD Doers Guild Internet Solutions Pvt. Ltd.
