### ISSUE TITLE
hello, please i have some problem with rendering of print, the full link href of balise <a> is seen 

### ISSUE THREAD

**Issue by fabirus** [DoersGuild/jQuery.print#33]

**Comment by sathvikp** [comment]
Could you kindly create a simple demo on JSFiddle
<http://t.sidekickopen33.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LqWkjW6443-21q0T7nW3Ljg7x56dK-rf8GfzwT02?t=https%3A%2F%2Fjsfiddle.net%2F&si=5680052904132608&pi=fb6d14b4-ba45-4ee3-9fe4-550dff88f40d>
or a similar site so that I can better understand your issue?

Thanks

On 9 December 2015 at 15:14, fabirus <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DoersGuild/jQuery.print/issues/33>.
>



-- 
Sathvik
Doers' Guild
<http://t.sidekickopen33.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LqWkjW6443-21q0T7nW3Ljg7x56dK-rf8GfzwT02?t=http%3A%2F%2Fwww.doersguild.com%2F&si=5680052904132608&pi=fb6d14b4-ba45-4ee3-9fe4-550dff88f40d>
RWD Doers Guild Internet Solutions Pvt. Ltd.

**Comment by fabirus** [comment]
the demo http://jsfiddle.net/fabirus/7gy3sape/3/embedded/result/

**Comment by sathvikp** [comment]
Thanks,

You can hide that bit with the following CSS:
```css
@media print {
  a[href]:after {
    content: none !important;
  }
}
```

More info:
+ http://stackoverflow.com/a/14931127/937891
+ http://stackoverflow.com/a/12051232/937891

**Comment by fabirus** [comment]
it's working thanks very much
