### ISSUE TITLE
Don't understand. can you help?

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [DoersGuild/jQuery.print#42]
Hello Print team,

I copied and pasted the code below in a html5 page but nothing happens. What am I missing.
We included the necessary script references.
` ` `
                    <div id="ele1" class="a">
                        <h3>Element 1</h3>
                        <p>
                            Some random text.
                        </p>
                        <button class="print-link no-print" onclick="jQuery('#ele1').print()">
                            Print this
                        </button>
                    </div>
` ` `
Kind regards,
Mario

**Comment by sathvikp** [comment]
Perhaps there was an error that prevented the scripts from loading
correctly.
Please check your browser's console for possible clues.

**Comment by MarioVanDenEijnde** [comment]
Hello sathvikp,

Thanks for the quick reply. And yes I looked at the console
I opened the console but there is nothing happening at all. Both tested chrome and IE.

Kind regards,
Mario

**Comment by sathvikp** [comment]
Strange, are you able to print as expected with the demo
<http://t.sidekickopen50.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LqWkjW6443-21q0T7nW3Ljg7x56dK-rf8GfzwT02?t=https%3A%2F%2Fdoersguild.github.io%2FjQuery.print%2Fdemo%2F&si=5680052904132608&pi=ac32210d-ad80-42c0-a09c-3ac711ef6c43>
?
And could you please:

   1. Ensure that the scripts are included correctly and in the right order
   - jQuery before jQuery.print and that their paths are correct
   2. Create a quick jsfiddle
   <http://t.sidekickopen50.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LqWkjW6443-21q0T7nW3Ljg7x56dK-rf8GfzwT02?t=https%3A%2F%2Fjsfiddle.net%2F&si=5680052904132608&pi=ac32210d-ad80-42c0-a09c-3ac711ef6c43>
   with your sample code so that I can have a look and help you further


On 29 March 2016 at 19:42, Mario <notifications@github.com> wrote:

> Hello sathvikp,
>
> Thanks for the quick reply. And yes I looked at the console
> I opened the console but there is nothing happening at all. Both tested
> chrome and IE.
>
> Kind regards,
> Mario
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/DoersGuild/jQuery.print/issues/42#issuecomment-202911576>
>



-- 
Sathvik
Doers' Guild
<http://t.sidekickopen50.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LqWkjW6443-21q0T7nW3Ljg7x56dK-rf8GfzwT02?t=http%3A%2F%2Fwww.doersguild.com%2F&si=5680052904132608&pi=ac32210d-ad80-42c0-a09c-3ac711ef6c43>
RWD Doers Guild Internet Solutions Pvt. Ltd.

**Comment by MarioVanDenEijnde** [comment]
Hello sathvikp,

Sorry for waiting but I did some more tests. We work on a Single Application page (javascript + css + html5) and this could be part of this page.
So it is not so easy to make a jsfiddle just for this piece.

I copy pasted the complete container div inside the page and at the bottom the scripts are referenced in the right order.

The only console response I get is an error with 2 of the 5 buttons saying that "jQuery.print is not a function".
Does that tell you something?

As you say maybe something is blocking the execution but I don't know how to investigate what might causing this.

Kind regards,
Mario

**Comment by sathvikp** [comment]
Yes - that likely means the jQuery.print plugin never loaded.
What do the other messages say? - also include warnings
Please keep your console open while you refresh the page so that all errors
are logged

On 29 March 2016 at 20:07, Mario <notifications@github.com> wrote:

> Hello sathvikp,
>
> Sorry for waiting but I did some more tests. We work on a Single
> Application page (javascript + css + html5) and this could be part of this
> page.
> So it is not so easy to make a jsfiddle just for this piece.
>
> I copy pasted the complete container div inside the page and at the bottom
> the scripts are referenced in the right order.
>
> The only console response I get is an error with 2 of the 5 buttons saying
> that "jQuery.print is not a function".
> Does that tell you something?
>
> As you say maybe something is blocking the execution but I don't know how
> to investigate what might causing this.
>
> Kind regards,
> Mario
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/DoersGuild/jQuery.print/issues/42#issuecomment-202926666>
>



-- 
Sathvik
Doers' Guild
<http://t.sidekickopen50.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LqWkjW6443-21q0T7nW3Ljg7x56dK-rf8GfzwT02?t=http%3A%2F%2Fwww.doersguild.com%2F&si=5680052904132608&pi=47ae3aa8-c8de-43f3-f4c0-1bc05a3df8e5>
RWD Doers Guild Internet Solutions Pvt. Ltd.

**Comment by MarioVanDenEijnde** [comment]
I just tested: "You are running jQuery version: 2.0.3" 

And I also include a console.log string in the jquery.print.js.
like follows:
jQuery.fn.print = function(){
	console.log("jQuery.fn.print");

And it fires only with this block. Not the other buttons on the page.
` ` `
                    <div id="ele1" class="a">
                        <h3>Element 1</h3>
                        <p>
                            Some random text.
                        </p>
                        <button class="print-link no-print" onclick="jQuery('#ele1').print()">
                            Print this
                        </button>
                    </div>
` ` `

**Comment by MarioVanDenEijnde** [comment]
Hello sathvikp,

I tried another demo page and got it working now. ;-)
But question: Do you have an idea how we could include a (dynamic) page break when the page is too long for one page?

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Hum. Only the first page is printed in chrome. In IE it prints all pages.

Am I missing something?

Kind regards,
Mario

**Comment by sathvikp** [comment]
You can force a page break with the CSS `page-break-after` and `page-break-before` properties
- https://davidwalsh.name/css-page-breaks
- http://www.w3schools.com/cssref/pr_print_pageba.asp

> Only the first page is printed in chrome. In IE it prints all pages

I'm not sure I understand this correctly - is some of the printed element's content not showing up in the print preview? If so could you please double check your print options? Because this plugin doesn't explicitly deal with pages and dumps all of the selected element's content for printing.
