### ISSUE TITLE
Sometimes the print preview appears blank

### ISSUE THREAD

**Issue by prem-kumar-e** [DoersGuild/jQuery.print#43]
Trying to print a barcode with some Text values. But sometimes the print preview appears blank. Once I reload the page it works. Why is this happening? How to overcome this ?

**Comment by mostafa-zahran** [comment]
I had the same issue but while investigating it I found that barcode is rendered as canvas 
just render it as img tag and it should work find

```javascript
var image_div = $('{{NEW_IMAGE_TAG}}');
var canvas_div = $('{{BARCODE_CANVAS_ID}}');
if (image_div.length > 0 && canvas_div.length > 0) {
  image_div.html("<img src='" + canvas_div.children()[0].toDataURL("image/png") + "' alt='from canvas'/>");
}
```

**Comment by prem-kumar-e** [comment]
But I am using CSS for barcode Rendering

**Comment by sathvikp** [comment]
Could you kindly check with the latest version v1.5.0 and let me know if the issue persists?
Also kindly experiment with larger [`timeouts`](https://github.com/DoersGuild/jQuery.print#timeout) to see if they help. Similarly try the [`iframe: false`](https://github.com/DoersGuild/jQuery.print#iframe) mode
Thanks!

**Comment by guncebektas** [comment]
+1 same issue

**Comment by touqeer-wal** [comment]
any update ? i'm getting the same problem

**Comment by sathvikp** [comment]
@touqeer-wal Does setting a larger [`timeout`](https://github.com/DoersGuild/jQuery.print#timeout) or using the [`iframe: false`](https://github.com/DoersGuild/jQuery.print#iframe) mode make any difference?

Thanks!

**Comment by touqeershafi** [comment]
I've set `globalStyle` option to false which fixed the issue. I think its due to bootstrap css which I'm using in my project.  `Iframe` false does not solve this issue.

**Comment by sathvikp** [comment]
@touqeershafi, that makes sense. 

The plugin works by putting your selected element and other attached [`globalStyles`](https://github.com/DoersGuild/jQuery.print/blob/66ca7772e3c1e0b418e89e1790d85612ae96bd79/jQuery.print.js#L174) in a new, hidden iframe (or window) before printing it. 

It would appear that the print is getting triggered while bootstrap and other dependencies are still being downloaded.

So, as an alternative to avoiding loading them completely with the `globalStyles: false` option, setting a larger timeout like `timeout: 1500`, and [caching](https://varvy.com/pagespeed/leverage-browser-caching.html) and [minifying](https://developers.google.com/speed/docs/insights/MinifyResources) your printable dependencies so that they load faster should help

(Note: WIth v1.5.0, the [timeout option](https://github.com/DoersGuild/jQuery.print#timeout) now works as a fallback for when [`$(frameWindow).on("load", callPrint);`](https://github.com/DoersGuild/jQuery.print/blob/66ca7772e3c1e0b418e89e1790d85612ae96bd79/jQuery.print.js#L56) fails to trigger soon enough)

**Comment by melloware** [comment]
I am using a canvas to try and print ChartsJS charts and have tried `print({globalStyles:false,timeout:1500, iframe: false});` and none of it works.  Changing my canvas to an image is not an option.

**Comment by melloware** [comment]
OK the real issue is that jQuery.clone does not clone canvas elements.  See: https://stackoverflow.com/questions/41239428/jquery-clone-does-not-clone-content-of-canvas

**Comment by CitizenOfRome** [comment]
v1.6.1: Added full canvas support - https://doersguild.github.io/jQuery.print/demo/
Thanks!
