### ISSUE TITLE
点击打印。打印内容可以显示其他页面内容吗？

### ISSUE THREAD

**Issue by menglyf** [DoersGuild/jQuery.print#72]
不打印本页面内容，是有可以指定路径打印其他页面

**Comment by sathvikp** [comment]
[via Google Translate](https://translate.google.com/#zh-CN/en/%E7%82%B9%E5%87%BB%E6%89%93%E5%8D%B0%E3%80%82%20%E5%8F%AF%E4%BB%A5%E6%89%93%E5%8D%B0%E5%86%85%E5%AE%B9%E6%98%BE%E7%A4%BA%E5%85%B6%E4%BB%96%E9%A1%B5%E9%9D%A2%E5%86%85%E5%AE%B9%E5%90%97%EF%BC%9F%20%EF%BC%8372%0A%E4%B8%8D%E8%A6%81%E6%89%93%E5%8D%B0%E6%AD%A4%E9%A1%B5%E9%9D%A2%E5%86%85%E5%AE%B9%EF%BC%8C%E8%BF%98%E6%9C%89%E5%85%B6%E4%BB%96%E9%A1%B5%E9%9D%A2%E5%8F%AF%E4%BB%A5%E6%8C%87%E5%AE%9A%E8%A6%81%E6%89%93%E5%8D%B0%E7%9A%84%E8%B7%AF%E5%BE%84), read that as

> Click to print. Can print content display other page content?
> Do not print this page content, there are other pages that can specify the path to print

-----------

我不完全明白你的问题，如果您想在打印后显示其他内容，可以使用延期选项，请参阅维基页面 - https://github.com/DoersGuild/jQuery.print/wiki/Using-the-deferred-option-to-set-up-a-callback-after-printing

如果您要打印不同页面的内容，您可以尝试将其加载到iframe中，然后打印，请参阅 - https://stackoverflow.com/questions/9616426/javascript-print-iframe-contents-only

I'm not entirely sure I understood your question, if you would like to display some other content after printing, you can use the deferred option, please see the Wiki page - https://github.com/DoersGuild/jQuery.print/wiki/Using-the-deferred-option-to-set-up-a-callback-after-printing

In case you're looking to print contents of a different page, you could perhaps try loading it in an iframe and then printing it, see - https://stackoverflow.com/questions/9616426/javascript-print-iframe-contents-only

**Comment by menglyf** [comment]
谢谢！另外问一个问题。打印的时候为什么会有一个空白页。怎么解决

**Comment by sathvikp** [comment]
> Thank you! Also ask a question. Why is there a blank page when printing? How to deal with it

如果你指的是最后的空白页，你必须使用CSS来调整你的页面，请参见http://stackoverflow.com/a/7847290/937891

如果它始终打印一个空白页面而不是内容，请尝试增加[超时值](https://github.com/DoersGuild/jQuery.print#timeout)，并删除打印内容中的任何外部CSS和JavaScript

If you are referring to additional blank pages at the end, you have to use CSS to adjust your page, see - http://stackoverflow.com/a/7847290/937891

If it is printing a blank page always instead of content, try increasing the [timeout value](https://github.com/DoersGuild/jQuery.print#timeout) and removing any external CSS and JavaScript inside the print content

**Comment by menglyf** [comment]
thank you! i've solved the problem!
