### ISSUE TITLE
Safari crashes when print dialog is cancelled and then  print is attempted again.

### ISSUE THREAD

**Issue by macsupport** [DoersGuild/jQuery.print#78]
If I click a print button using the plugin (this happens on your example page as well), and then cancel the print job, When I click Print a second time, I get a dialog 
 _This webpage is trying to print. Do you want to print this webpage?  Print or Cancel_. 
Safari then crashes if I click Print rather than Cancel.

**Comment by sathvikp** [comment]
What version of Safari are you on?
And does printing with window.print() work as expected?

On 16-Sep-2017 3:45 am, "Mike Sozanski" <notifications@github.com> wrote:

If I click a print button using the plugin (this happens on your example
page as well), and then cancel the print job, When I click Print a second
time, I get a dialog
*This webpage is trying to print. Do you want to print this webpage? Print
or Cancel*.
Safari then crashes if I click Print rather than Cancel.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DoersGuild/jQuery.print/issues/78>, or mute the thread

**Comment by macsupport** [comment]
window.print(); works as expected. Safari version 10.1.2

**Comment by sathvikp** [comment]
Sounds like an bug with the browser itself - have you tried asking in any product forums?
What version of Mac are you on?

**Comment by Lefystore** [comment]
This bug is still happening all the time on Safari, it's almost imposible to print more than once without refreshing the page.

**Comment by sathvikp** [comment]
@Lefystore Kindly let me know the following
- What version of Safari & OS are you on?
- Could you describe in a step-by-step manner what exactly is happening and at what point the browser crashes?
- Are you able to replicate the same on the demo page - https://doersguild.github.io/jQuery.print/demo/
Thanks!

**Comment by sathvikp** [comment]
@Lefystore Also does the `iframe: true` option affect this in any way?

**Comment by Lefystore** [comment]
@sathvikp Sure

- Using macOs Sierra V10.12.6 and Safari 11.0.
- Just try to print any element like $('#elem').print();, the first time you try it works fine, then you cancel the printing dialog and press the printing button again and Safari alerts that the page is trying to print, if you accept the browser crashes and close.
- It does happen on the demo too
- Also happens using the iframe option

It doesn't matter how you call the $(el).print() function, it works once, then crashes
