### ISSUE TITLE
Custom stylesheet demo doesn't seem to work

### ISSUE THREAD

**Issue by niccolomineo** [DoersGuild/jQuery.print#85]

**Comment by sathvikp** [comment]
The problem is that the [Google Font CSS](https://fonts.googleapis.com/css?family=Inconsolata) only defines the font but does not apply it to any elements, you will need to manually add in the CSS to apply the font to your element (which we haven't done on the demo)
If you're saying that the font is not applied despite this, kindly create an example JSFiddle demo replicating the issue so that I can help you out.
Thanks!
